### PR TITLE
Add support for libswaykbswitch

### PR DESCRIPTION
**Pull request by khaser**
Issue #55 

I wrote [little rust library](https://github.com/khaser/sway-vim-kbswitch) to use xkbswitch with sway using socket inter-process communication.

### CODE REVIEW

**Comment by lyokha** [comment]
Does this fix #55?

**Comment by khaser** [comment]
Partly. Motions like f{char} doesn't work. Also there are several problems with execution with sudo, but it can be solved by ``--preserve-env=SWAYSOCK`` argument.

**Comment by lyokha** [comment]
They are not big problems. `f{char}` is not naturally supported, it only works in the Keymap assistance mode.
Do you want to put a note about Sway support in the README? (there is a list of supported platforms at the end of section *About*).

**Comment by khaser** [comment]
Done. I forgot about this

**Comment by lyokha** [comment]
Merged. Thanks!

**Pull request merged**
